### PR TITLE
Remove columns from final trip table, fix error when SAS URL is invalid

### PR DESCRIPTION
**Pull request by aber-sandag**
Fixes [AB#373](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/373)
Fixes [AB#375](https://dev.azure.com/SANDAG-ADS/3af839ac-e181-4605-b11c-60f38a706246/_workitems/edit/375)

https://dev.azure.com/SANDAG-ADS/ORTAD/_workitems/edit/373
https://dev.azure.com/SANDAG-ADS/ORTAD/_workitems/edit/375

### CODE REVIEW

**Comment by aber-sandag** [comment]
Conflicts have been resolved locally, currently testing before pushing

**Review by anneku — APPROVED** [review]
The outputs are much easier to read now without all those extra columns.  And any new columns will still be captured in the outputs.

**Comment by anneku** [comment]
@JoeJimFlood adding outputs.yaml to common config directory.  Just want to make sure that makes sense to you as a good location.

**Comment by JoeJimFlood** [comment]
@anneku If it's used by multiple models than yes

**Pull request merged**
