### PR TITLE
ABM2 Plus Airport Model Improvement

### PR DESCRIPTION
**Pull request by i-am-sijia**

### CODE REVIEW

**Comment by i-am-sijia** [comment]
@wusun2 This is the latest Java codes for ABM2+ airport model update.

**Comment by wusun2** [comment]
@i-am-sijia , have you successfully run a complete ABM2+ (14.2.1 release) scenario (maybe base year 2016) with the updated Airport model integrated?  There were some issues when integrating updated airport model with ABM1, we need to make sure when we integrate it with ABM2+, these issues are all resolved.

**Comment by i-am-sijia** [comment]
@wusun2, no I'm testing only the airport model since I don't have access to the complete model and scenarios.  I've been reviewing and updating ABM2+ airport model in case any common issues are discovered while the team (Mike) runs ABM1.

**Comment by kulshresthaa** [comment]
@wusun2 Could you please review this PR and let us know if you have any comments. We would like to get the airport model changes merged to the official SANDAG ABM release and then use the new jar for the updated model run.

**Comment by i-am-sijia** [comment]
Hi @wusun2, we created a jar file with the airport updates as well as the latest ABM2 Trunk codes. @kulshresthaa has let me know the SANDAG full model ran successfully with the new jar.  There should be no issue merging airport codes into ABM2 Trunk. If you agree, we can merge and close this pull request.

**Comment by wusun2** [comment]
@i-am-sijia , glad to know the airport model is integrated with the core model.  What the progress on two additional items? 1) run the base year model, and make sure the base year validation metrics are good 2) loading the updated airport model results into the database?  If both have passed, we can accept the PR.

**Comment by i-am-sijia** [comment]
@kulshresthaa, will you please answer Wu's questions?

**Comment by kulshresthaa** [comment]
> 

@wusun2 although the model ran successfully with the new software and updated airport model, there are issues with getting the data load process to work, as the format of the airport model output file has changed.  The actual changes in the data load process to incorporate the format change will happen (as per Mike C) after a few months as part of the next release. Meanwhile, we are trying some workarounds to get past the data load step. At this point, we are working towards getting the updated run loaded into the database so that can then look at the base year validation metrics. 

cc @i-am-sijia

**Comment by wusun2** [comment]
Approved per 6/10/22 meeting with WSP.

**Comment by wusun2** [comment]
approved and merged

**Pull request merged**
